####服务器端口号
server:
  port: 9100
##定义服务名称
spring:
  application:
    name: fqyd-eureka
eureka:
  instance:
    ####服务注册ip
    hostname: 127.0.0.1
  client:
    ###因为本身是注册中心，是否需要将自己注册给自己的注册中心(集群的时候需要设置成true)
    registerWithEureka: true
    ###因为本身是注册中心,不需要去检索服务
    fetchRegistry: true
    ###注册地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
    server:
      ##测试时关闭，自我保护机制，保证不可用服务及时踢出
      enable-self-preservation: false
      ### 清理间隔（单位毫秒，默认是60*1000）
      eviction-interval-timer-in-ms: 2000
